# Sử dụng image python nhẹ
FROM python:3.9-slim

# Thiết lập thư mục làm việc
WORKDIR /app

# Copy file code vào trong container
COPY app.py .

# Lệnh chạy khi container khởi động
CMD ["python", "app.py"]