global:
  scrape_interval: 15s # Thu thập dữ liệu mỗi 15 giây

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter' # Đây là service thu thập thông tin máy tính của bạn
    static_configs:
      - targets: ['node-exporter:9100']